<!DOCTYPE html>
<html lang="ka">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- CSS -->
    <link rel="stylesheet" href="/style.css">

    <title>${title}</title>
</head>
<body>

<header>
    <nav>
        <div class="brand">Autotrust Georgia</div>
        <ul class="nav-links">
            <li><a href="/">მთავარი</a></li>
            <li><a href="#">ჩვენს შესახებ</a></li>
            <li><a href="#">სერვისები</a></li> 
        </ul>
    </nav>
</header>

<main>
    <h1>${title}</h1>

    <div class="services-container">

        <div class="service-card">
            <img src="/imiges/1665561414.jpg" alt="ზეთი">
            <h2>ძრავის ზეთი</h2>
            <a href="/oil" class="btn">ნახვა</a>
        </div>

        <div class="service-card">
            <img src="/imiges/IMG_0268.png" alt="ანტიფრიზი">
            <h2>ანტიფრიზი</h2>
            <a href="#" class="btn">ნახვა</a>
        </div>

        <div class="service-card">
            <img src="/imiges/12642720_1.jpg" alt="აკუმლატორი">
            <h2>აკუმლატორი</h2>
            <a href="#" class="btn">ნახვა</a>
        </div>

    </div>
</main>

<footer>
    <p>© 2024 ავტოსერვისი</p>
</footer>

</body>
</html>