<!DOCTYPE html>
<html lang="ka">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>ძრავის ზეთები</title>

    <!-- CSS -->
    <link rel="stylesheet" href="/oil.css">
</head>
<body>

<header>
    <nav>
        <div class="brand">Autotrust Georgia</div>
        <ul class="nav-links">
            <li><a href="/">მთავარი</a></li>
        </ul>
    </nav>
</header>

<main>
    <h1>ძრავის ზეთები</h1>
</main>

<div class="products">

    <div class="card">
        <h2>Castrol EDGE 5W-30</h2>
        <img src="/imiges/12642720_11.jpg">
        <p>ფასი: 30₾</p>
        <button>კალათაში დამატება</button>
    </div>

    <div class="card">
        <h2>Mobil 1 5W-40</h2>
        <img src="/imiges/00_00004685_dc3d1e92.jfif">
        <p>ფასი: 90₾</p>
        <button>კალათაში დამატება</button>
    </div>

    <div class="card">
        <h2>Liqui Moly 10W-40</h2>
        <img src="/imiges/liquimoly.jpg">
        <p>ფასი: 80₾</p>
        <button>კალათაში დამატება</button>
    </div>

</div>

<footer>
    <p>© 2024 ავტოსერვისი</p>
</footer>

</body>
</html>